version: '2.4'
services:

  transmission-app:
    image: tiredofit/transmission:latest
    container_name: transmission-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission-app.rule=Host(`transmission.example.com`)
      - traefik.http.services.transmission-app.loadbalancer.server.port=80
    volumes:
      - ./data:/data
    environment:
      - CONTAINER_NAME=transmission-app
      - CONTAINER_LOG_LEVEL=INFO
      - USER_APP=1000
      - GROUP_APP=1000
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
